export const GET_COIN_PRICE = "GET_COIN_PRICE"
export const GET_COIN_PRICE_SUCCESS = "GET_COIN_PRICE_SUCCESS"
export const API_COIN_EXCHANGE_ERROR = "API_COIN_EXCHANGE_ERROR"


export const DO_SWAP_COIN = 'DO_SWAP_COIN'
export const DO_SWAP_COIN_SUCCESS = 'DO_SWAP_COIN_SUCCESS'
